apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: examer-front
spec:
  selector:
    matchLabels:
      app: examer-front
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: examer-front
    spec:
      #imagePullSecrets:
       # - name: registry-container-registry-secret
      containers:
        - name:  examer-front
          image: examer-front:latest
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
# The port that the container is running on in the cluster
